# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

sh_library(
    name = "john",
    visibility = ["//visibility:public"],
    deps = ["//cars:74383"],
)

sh_library(
    name = "amy",
    tags = ["female"],
    visibility = ["//visibility:public"],
)

sh_library(
    name = "james",
    visibility = ["//visibility:public"],
)

sh_library(
    name = "olivia",
    visibility = ["//visibility:public"],
)

sh_library(
    name = "michelle",
    visibility = ["//visibility:public"],
)

sh_library(
    name = "robert",
    visibility = ["//visibility:public"],
)

sh_library(
    name = "basil",
    tags = ["tall"],
    visibility = ["//visibility:public"],
    deps = ["//cars:23245"],
)

sh_library(
    name = "katie",
    tags = ["small"],
    visibility = ["//visibility:public"],
    deps = ["//cars:85465"],
)

sh_library(
    name = "mark",
    tags = ["small"],
    visibility = ["//visibility:public"],
)
